---
title: "Build and Test Enviroment"
author: "Craig Parman"
date: "10/5/2016"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##Introduction

This document lists the R version and package vesions used in the development of the CoreAPIV2 package.  
It is built automatically and refects the latest vesions used. 

## CoreAPIV2 Package Information

```{r echo = FALSE }

p<-packageDescription("CoreAPIV2")


show(p)

```

##R Environment


```{r echo = FALSE}

library('knitr')
s<-sessionInfo()
envrio<-as.data.frame(s$R.version)

##R Environment

kable(  envrio[,1:5] , format = "markdown")
kable(  envrio[,6:10] , format = "markdown")
kable(  envrio[,11:length(envrio)] , format = "markdown")

```


##Required Package Version



```{r echo = FALSE}
library('knitr')
d<-packageDescription("CoreAPIV2")
imports<-strsplit(d$Imports,",")[[1]]
n<-length(imports)
versions<-sapply(imports,function(x) packageDescription(x)$Version)

importframe<-data.frame(package = imports, vesion = versions)

kable(importframe , format = "markdown")

```

Results for unit tests

```{r echo = FALSE}
library('knitr')
library('testthat')

 
log<-capture.output(tr<-test_dir("../tests/testthat"))

fr <- as.data.frame(tr)  

fr

kable(as.data.frame(tr),longtable = TRUE,font_size = 7)

```



